baseURL = "//www.hazrulazhar.com"
languageCode = "en-SG"
title = "Hazrul Azhar Jamari. Technopreneur based in Singapore."
theme = "hugo-split-theme"
publishDir = "docs"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Family"
    pre = "edit"
    url = "/family-man/"
    weight = 2
  [[menu.main]]
    name = "Foodie"
    pre = "tag"
    url = "/foodie/"
    weight = 3
  [[menu.main]]
    name = "Tech"
    pre = "tag"
    url = "/tech-community/"
    weight = 4

[params]
  dateFormat = "Jan 2, 2006"

# Metadata for search engines and social sharing
  author = "Hazrul Azhar"
  description = "Hazrul is a technopreneur and software engineer who loves building elegant solutions for E-Commerce in Southeast Asia."
  shareImage = "background1.jpg"
  twitterHandle = "hazrulazhar"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "background1.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

    # Links List #1
    [[params.links]]
      [params.links.list1]
        heading = "Articles"

        [[params.links.list1.link]]
          text = "Blog"
          url = "/blog"
        [[params.links.list1.link]]
          text = "Media"
          url = "/media"


    # Links List #2
    [[params.links]]
      [params.links.list2]
        heading = "Social"

        [[params.links.list2.link]]
          text = "LinkedIn"
          url = "https://www.linkedin.com/in/hazrulazhar"
        [[params.links.list2.link]]
          text = "Github"
          url = "https://www.github.com/hazrulazhar"
        [[params.links.list2.link]]
          text = "Facebook"
          url = "https://www.facebook.com/hazrulazhar.co"

    # Links List #3
    [[params.links]]
      [params.links.list3]
        heading = "Network"

        [[params.links.list3.link]]
          text = "Contact Me"
          url = "mailto: hi@hazrulazhar.com"